before_script:
  # If during build on WindowsDesktop runner, you get some errors about long of file for example: 
  # "error: unable to create file... : Filename too long "
  # run your build with this command once ( on linux machine this will cause an error: Permission denied )
  #- git config --system core.longpaths true
  #- git config --local include.path "$PWD"/.gitconfig
  # If you encounter error:
  # 'fatal: Could not read from remote repository.'
  # It is possible that WindowsDesktop runner doesn't have set USERPROFILE
  # It needs to be setted through script, for example:
  - set USERPROFILE=C:\Users\gitlab-runner

  - git submodule sync --recursive
  - git submodule update --init --recursive 
  - git submodule foreach git pull origin master
  #- git submodule foreach --recursive git checkout master && git pull origin master



stages:
  - wizard
  - installers
  - documentation


generate_wizard:
  stage: wizard
  script: scripts/wizard_generator/generator.sh > wizard.json
  tags:
  - LinuxDesktop
  artifacts:
    paths:
    - wizard.json
    #expire_in: 20 minutes


build_linux_wizard_installer:
  stage: installers
  variables:
    MILO_SERVER: "https://seafile.milosolutions.com"
  script:
    - scripts/wizard_generator/build_and_upload.sh
  tags:
    - LinuxDesktop

build_windows_wizard_installer:
  stage: installers
  variables:
    MILO_SERVER: "https://seafile.milosolutions.com"
  script:
    - powershell -ExecutionPolicy RemoteSigned -File scripts/wizard_generator/build_and_upload_win.ps1
  tags:
    - WindowsDesktop

build_docs:
  stage: documentation
  script:
    # run doxygen with the appropriate doxyfile
    - doxygen $CI_PROJECT_NAME.doxyfile

    # move generated documentation to qtdocs/milo-code-db/$CI_PROJECT_NAME
    - rm -rf /opt/online_docs/www/qtdocs/milo-code-db/wizard/
    - mv doc/html /opt/online_docs/www/qtdocs/milo-code-db/wizard/
  tags:
    - Docs
